apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-quote
  labels:
    app: sm-demo
spec:
  scaleTargetRef:
    apiVersion: apps.openshift.io/v1
    kind: Deployment
    name: quote
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 50